"""
Django settings for ThreeDModeler project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Authentication.apps.AuthenticationConfig',
    'two_factor1.apps.two_factor1Config',
    'allauth',
    'allauth.account',
    'allauth_microsoft',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_email',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'two_factor.plugins.email',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ThreeDModeler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ThreeDModeler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
from django.contrib.auth.password_validation import validate_password

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
                'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'Authentication.forms.CustomUserAttributeSimilarityValidator',
        'OPTIONS': {
                'user_attributes': ('email', 'username'),
                'max_similarity': 0.6,
        }
    },
    {
        'NAME': 'Authentication.forms.MinimumUpperCaseValidator',
        'OPTIONS': {
            'min_uppercase': 1,
        },
    },
    {
        'NAME': 'Authentication.forms.MinimumLowerCaseValidator',
        'OPTIONS': {
            'min_lowercase': 1,
        },
    },
    {
        'NAME': 'Authentication.forms.MinimumDigitValidator',
        'OPTIONS': {
            'min_digits': 1,
        },
    },
    {
        'NAME': 'Authentication.forms.MinimumSpecialCharacterValidator',
        'OPTIONS': {
            'min_special_characters': 1,
        },
    },
    {
        'NAME': 'Authentication.forms.MaximumSimilarCharactersValidator',
        'OPTIONS': {
            'max_characters': 3,
        },
    },
    {
        'NAME': 'Authentication.forms.SignupPasswordContainsUsernameValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'Authentication.CustomUser'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

TWO_FACTOR_PATCH_ADMIN = False
LOGIN_URL = 'account_login'


LOGIN_REDIRECT_URL = '/profile/'

LOGOUT_REDIRECT_URL = '/accounts/login/'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

ACCOUNT_ADAPTER = 'Authentication.adapters.CustomAccountAdapter'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online', 'prompt': 'select_account'},
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        }
    },

    'microsoft': {
        'AUTH_PARAMS': {
            'prompt': 'select_account',
            'nonce': 'defaultnonce'
        },
        'SCOPE': ['User.Read', 'email', 'openid'],
        'APP': {
            'client_id': '',
            'secret': '',
            'key': '',
            'authorization_url': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
            'access_token_url': 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
            'logout_url': 'https://login.microsoftonline.com/common/oauth2/logout',
            'login_url': 'https://login.microsoftonline.com/common/oauth2/authorize',
            'TENANT': '',
            'response_type': 'code',
            'redirect_uri': 'http://localhost:8000/auth/accounts/microsoft/login/callback/',
        }
    }

}


# Disable rate limiting during testing
# Make sure to delete this or adjust this
ACCOUNT_RATE_LIMITS = {
    "manage_email": "1/m",
}
