# Generated by Django 4.1.7 on 2023-03-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_updated',
            field=models.BooleanField(default=False),
        ),
    ]
